<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFihUpgx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFihUpgx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFihUpgx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFihUpgx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFihUpgx\App_KernelDevDebugContainer([
    'container.build_hash' => 'FihUpgx',
    'container.build_id' => 'da696245',
    'container.build_time' => 1631284429,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFihUpgx');
